### ISSUE TITLE
Doesn't work for 21.10

### ISSUE THREAD

**Issue by adefaria** [ManishOnLinux/ubuntu-gdm#2]
Doesn't work:

Earth:sudo ./ubuntu-gdm.sh /Pictures/Naughty\ Dog/Last\ of\ Us\ 2.jpg 
This script only works with Ubuntu 20.04 (focal fossa) and above....Exiting.
    Script by : Manish Singh Parmar (github.com/SirParmar)
Earth:lsb_release -id
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Earth:

**Comment by SirParmar** [comment]
Dear Andrew,
Thanks for your feedback, I've updated the lsb_release check command, which
checks for distro version.

Hope the script works now, please check and get back to me.

Stay Home - Fun Linux - Stay Safe!
